project_id = "zbniouzrkbkyvkpnpwxa"

[functions.verify-pin]
verify_jwt = false

[functions.cleanup-trash]
verify_jwt = false

[functions.fetch-tiktok-metadata]
verify_jwt = false

[functions.vault-data]
verify_jwt = false

[functions.fetch-link-metadata]
verify_jwt = false

[functions.verify-shared-album]
verify_jwt = false

[functions.access-shared]
verify_jwt = false
